export default {
  SET_ORDER: 'SET_ORDER',

  ADD_ALERT: 'ADD_ALERT',
  DISMISS_ALERT: 'DISMISS_ALERT',
  CLEAR_ALERTS: 'CLEAR_ALERTS',

  SET_AUTH_USER: 'SET_AUTH_USER',

  GET_USER: 'GET_USER',
  GET_CLIENTS_BY_PHONE: 'GET_CLIENTS_BY_PHONE',

  REMOVE_GLOBAL_SCAN_LAST_CHAR: 'REMOVE_GLOBAL_SCAN_LAST_CHAR',
  SET_SCAN_STRING_ACTION: 'SET_SCAN_STRING_ACTION',
  CLEAR_GLOBAL_SCAN_STRING: 'CLEAR_GLOBAL_SCAN_STRING',
  ADD_GLOBAL_SCAN_CHAR: 'ADD_GLOBAL_SCAN_CHAR',
}
